In [191]:
import pandas as pd
import numpy as np
from math import floor
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("iris.csv")
data.head()

   sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [13]:
# Simple Sampling
np.random.seed(4327)
sampling = np.random.choice(a=[0,1], size=150, replace=True, p=[0.8, 0.2])
simpleSampling = data[sampling==1]
simpleSampling.head()

    sepal length  sepal width  petal length  petal width        class
6            4.6          3.4           1.4          0.3  Iris-setosa
9            4.9          3.1           1.5          0.1  Iris-setosa
14           5.8          4.0           1.2          0.2  Iris-setosa
21           5.1          3.7           1.5          0.4  Iris-setosa
25           5.0          3.0           1.6          0.2  Iris-setosa

In [190]:
# Systematic Sampling
total = 150
quantSamples = 15
sampling2 = []
k = floor(total/quantSamples)

index = (np.random.randint(low=0, high= k, size=1))[0]

for i in range(quantSamples):
    sampling2.append(index)
    index+=k

systematicSampling = data.loc[sampling2]
systematicSampling.head()

    sepal length  sepal width  petal length  petal width        class
6            4.6          3.4           1.4          0.3  Iris-setosa
16           5.4          3.9           1.3          0.4  Iris-setosa
26           5.0          3.4           1.6          0.4  Iris-setosa
36           5.5          3.5           1.3          0.2  Iris-setosa
46           5.1          3.8           1.6          0.2  Iris-setosa

In [203]:
# Stratified Sampling
x,_,stratifiedSampling, _ = train_test_split(data.iloc[:,0:4], data.iloc[:,4], test_size=0.8, stratify=data.iloc[:,4])
stratifiedSampling.head()

11        Iris-setosa
4         Iris-setosa
95    Iris-versicolor
91    Iris-versicolor
87    Iris-versicolor
Name: class, dtype: object